"""Add new_field to User

Revision ID: d05a6c9ab96b
Revises: 
Create Date: 2025-02-01 13:00:07.337735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd05a6c9ab96b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('day_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('day_name',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    op.create_table('data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day_name', sqlite.JSON(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
